<?php

/**
 * @file CNX_UIDevelopment.module
 *
 * This module carries the user interface templates, css & JS required to user interfaces.
 */

require_once(dirname(dirname(__FILE__)) . "/Classes/Coconnex/Utils/Handlers/TemplateHandler.Class.php");
require_once(dirname(dirname(__FILE__)) . "/Classes/Coconnex/Utils/Handlers/AssetHandler.Class.php");
require_once(dirname(dirname(__FILE__)) . "/Classes/Coconnex/Utils/Handlers/MessageHandler.Class.php");

use Coconnex\Utils\Handlers\AssetHandler;
use Coconnex\Utils\Handlers\TemplateHandler;
use Coconnex\Utils\Handlers\MessageHandler;

function CNX_UIDevelopment_menu()
{
    $items['uidev/floorplan'] = array(
        'title' => t('Self Service Floorplan UI Components'),
        'page callback' => 'CNX_UIDevelopment_ss_floorplan_components',
        'type' => MENU_CALLBACK,
        'access arguments' => array('Access UI Development'),
    );
    $items['uidev/welcomepage'] = array(
        'title' => t('Self Service Welcome Page UI Components'),
        'page callback' => 'CNX_UIDevelopment_ss_welcome_page',
        'type' => MENU_CALLBACK,
        'access arguments' => array('Access UI Development'),
    );


    return $items;
}

function CNX_UIDevelopment_perm()
{
    return array('Access UI Development');
}

function CNX_UIDevelopment_ss_floorplan_components()
{
    global $base_url;
    MessageHandler::add("This is a test message");
    drupal_set_message("This is a Drupal test message");
    AssetHandler::add_asset("/assetscdn/fp_toolbar/styles/fp_toolbar.css", "stylesheet");
    AssetHandler::add_asset("/assetscdn/fp_controls/styles/fp_controls.css", "stylesheet");
    AssetHandler::add_asset("/assetscdn/fp_toolbar/scripts/fp_toolbar.js", "script", null, true);
    AssetHandler::add_asset("/assetscdn/fp_controls/scripts/fp_controls.js", "script", null, true);
    $f_name = "floorplancontent.tpl.php";
    $tpl_path = dirname(__FILE__) . "/ss_floorplan_components/templates/";
    return TemplateHandler::applyTemplateFile($tpl_path, $f_name, array());
}
function CNX_UIDevelopment_ss_welcome_page()
{
    MessageHandler::add("This is a test message");
    $f_name = "welcome_page.tpl.php";
    $tpl_path = dirname(__FILE__) . "/welcome_page/templates/";
    return TemplateHandler::applyTemplateFile($tpl_path, $f_name, array());
}
