<?php

/**
 * @file CNX_DbEntities.module
 *
 * This module is used to generate database entity models for MySql & D6.
 */

require_once(dirname(dirname(__FILE__)) . "/Classes/Coconnex/DBFactory/DbEntities/DbEntitiesManager.Class.php");

use Coconnex\DBFactory\DbEntities\DbEntitiesManager;

function CNX_DbEntities_menu()
{
    $items['dbentities'] = array(
        'title' => t('Manage Databse Entities'),
        'page callback' => 'CNX_DbEntities_main',
        'type' => MENU_CALLBACK,
        'access arguments' => array('Access DbEntities'),
    );

    return $items;
}

function CNX_DbEntities_perm()
{
    return array('Access DbEntities');
}

function CNX_DbEntities_init()
{
}

function CNX_DbEntities_main()
{
    $MySqlEntities = new DbEntitiesManager('SelfService', 'MySql');
    //debug($MySqlEntities->entities);
    $MySqlEntities->generate();
    header('Content-Type: text/plain; charset=utf-8');
    exit;
}
