<?php

/**
 * @file CNX_UIDevelopment.module
 *
 * This module carries the user interface templates, css & JS required to user interfaces.
 */

require_once(dirname(dirname(__FILE__)) . "/Classes/Coconnex/Utils/Handlers/AssetHandler.Class.php");

use Coconnex\Utils\Handlers\AssetHandler;

function CNX_AssetsCDN_menu()
{
    $items['assetscdn'] = array(
        'title' => t('Asserting Assets'),
        'page callback' => 'CNX_AssetsCDN_assert',
        'type' => MENU_CALLBACK,
        'access arguments' => array('Access Asset CDN'),
    );

    return $items;
}

function CNX_AssetsCDN_perm()
{
    return array('Access Asset CDN');
}

function CNX_AssetsCDN_init()
{
    AssetHandler::$assets_cdn_base_path = dirname(__FILE__);
    AssetHandler::$cache_control_string = '?' . substr(variable_get('css_js_query_string', '0'), 0, 1);
}

function CNX_AssetsCDN_assert()
{
    AssetHandler::assert(arg());
}
