<?php
require_once(dirname(dirname(__FILE__)) . "/Classes/Coconnex/Utils/Handlers/TemplateHandler.Class.php");
require_once(dirname(dirname(__FILE__)) . "/Classes/Coconnex/Utils/Handlers/AssetHandler.Class.php");

use Coconnex\API\IFPSS\Exhibitor\Managers\CNXExhibitorManager;
use Coconnex\API\IFPSS\StandTransaction\Managers\StandTransactionManager;
use Coconnex\API\IFPSS\WaitingList\Collection\WaitingList;
use Coconnex\Integrations\Coconnex\BackendAPIClient\Order\Managers\APIOrderManager;
use Coconnex\Utils\Handlers\AssetHandler;
use Coconnex\Utils\Handlers\TemplateHandler;

/**
 * @file CNX_Order.module
 *
 * CNX Order module for manage orders.
 */
function CNX_Order_menu()
{
    $items['myorders'] = array(
        'title' => t('Order List'),
        'page callback' => 'CNX_Order_List',
        'type' => MENU_CALLBACK,
        'access arguments' => array('Access Orders'),
    );

    return $items;
}

function CNX_Order_perm()
{
    return array('Access Orders');
}

function CNX_Order_Lista()
{
    $vars = array();
    $outHTML = TemplateHandler::applyTemplateFile(drupal_get_path('module', 'CNX_Order') . "/templates/", 'my_stands_tabs.tpl.php', $vars);
    // echo $outHTML; die;
    return $outHTML;
}

function CNX_Order_List()
{
    global $user;
    $vars = array();
    $exhibitor_data = new CNXExhibitorManager(0, $user->uid);
	$exhibitorProfileStatus = $exhibitor_data->getExhibitorProfileStatus();

    if($exhibitorProfileStatus === false){
		drupal_goto('/profile/compulsory');
	}

    $customer_id = $exhibitor_data->exhibitor->external_ref_id;

    $template_base_path = drupal_get_path('module', 'CNX_Order') . "/templates/";
    $row_template_path = $template_base_path . "my_orders_row_cols3.tpl.php";

    $vars['template_base_path'] = $template_base_path;
    $vars['row_template_path'] = $row_template_path;

    $api_order_mgr = new APIOrderManager($customer_id, 'order_get');
    $api_order_mgr->get_orders();
    // debug($api_order_mgr);
    // return $api_order_mgr->order_response;
    // $vars = new WaitingList($user->uid,$user->roles, $customer_id);
    $response = json_decode($api_order_mgr->order_response);
    $orders = $response->data;
    // debug($orders,1);
    // $accepted_orders = array();
    // $confirmed_orders = array();
    $all_orders = array();
    $cancelled_orders = array();
    $order_id=array();
    if (is_array($orders) && sizeof($orders)) {
        foreach ($orders as $order) {
            // if($order->order_status == 'ACCEPTED'){
            //     $accepted_orders[] = $order;
            // }elseif($order->order_status == 'CONFIRMED'){
            //     $confirmed_orders[] = $order;
            // }elseif($order->order_status == 'CANCELLED'){
            //     $cancelled_orders[] = $order;
            // }

            if ($order->order_status == 'CANCELLED') {
                $cancelled_orders[] = $order;
            } else {
                $all_orders[] = $order;
            }
            if ($order->order_status == 'SUBMITTED') {
                $order_id[] = $order->order_id;
            }
        }
    }
    // $vars['accepted_orders'] = $accepted_orders;
    // $vars['confirmed_orders'] = $confirmed_orders;
    $vars['all_orders'] = $all_orders;
    $vars['cancelled_orders'] = $cancelled_orders;

    AssetHandler::add_asset("/assetscdn/orders/scripts/orders.js", "script");
    // debug($vars,1);
    $outHTML = TemplateHandler::applyTemplateFile(drupal_get_path('module', 'CNX_order') . "/templates/", 'my_orders.tpl.php', $vars);
    // echo $outHTML; die;
    return $outHTML;

}
