<?php

require_once(dirname(dirname(__FILE__)) . "/Classes/Coconnex/API/Reminders/Schedules/Managers/ReminderScheduleManager.Class.php");
use Coconnex\API\Reminders\Schedules\Managers\ReminderScheduleManager;

/**
 * @file CNX_Reminder.module
 *
 * For manage Reminder notifications.
 */
function CNX_Reminder_menu()
{
    $items['Reminder/Cron'] = array(
        'title' => t('Cron'),
        'page callback' => 'CNX_Reminder_cron',
        'type' => MENU_CALLBACK,
        'access arguments' => array('Manage Reminder'),
    );

    $items['Reminder/Schedule'] = array(
        'title' => t('Cron'),
        'page callback' => 'CNX_Reminder_execute_schedule',
        'type' => MENU_CALLBACK,
        'access arguments' => array('Manage Reminder'),
    );

    return $items;
}

function CNX_Reminder_perm()
{
    return array('Manage Reminder');
}

function CNX_Reminder_cron()
{

}

function CNX_Reminder_execute_schedule(){
    global $user;
    $schedule_id = arg(2);
    $schedule_mngr = new ReminderScheduleManager($user->uid,$schedule_id);
    debug($schedule_mngr);
}

function CNX_Reminder_schedule_execute($schedule_id){
    global $user;
    $schedule_mngr = new ReminderScheduleManager($user->uid,$schedule_id);
    watchdog('SCH_MGR',print_r($schedule_mngr,true));
}