<?php
require_once(dirname(dirname(__FILE__)) . "/Classes/Coconnex/API/IFPSS/BookingHistory/Managers/BookingHistoryManager.Class.php");
require_once(dirname(dirname(__FILE__)) . "/Classes/Coconnex/API/IFPSS/BookingHistory/Models/RequestModels/BookingHistoryRequestModel.Class.php");
require_once(dirname(dirname(__FILE__)) . "/Classes/Coconnex/API/IFPSS/BookingHistory/Collection/exhBookingHistory.Class.php");
require_once(dirname(dirname(__FILE__)) . "/Classes/Coconnex/API/IFPSS/Exhibitor/Managers/CNXExhibitorManager.Class.php");
require_once(dirname(dirname(__FILE__)) . "/Classes/Coconnex/Utils/Handlers/TemplateHandler.Class.php");

use Coconnex\API\IFPSS\BookingHistory\Managers\BookingHistoryManager;
use Coconnex\API\IFPSS\BookingHistory\Models\RequestModels\BookingHistoryRequestModel;
use Coconnex\API\IFPSS\BookingHistory\Collection\exhBookingHistory;
use Coconnex\API\IFPSS\Exhibitor\Managers\CNXExhibitorManager;
use Coconnex\Utils\Handlers\TemplateHandler;

function CNX_BookingHistory_menu() {

	$items['bookinghistory'] = array(
			'title' => t('Booking History'),
			'page callback' => 'CNX_booking_history',
			'access arguments' => array('Access Booking History'),
		);
	return $items;
}


function CNX_BookingHistory_perm(){
	return array('Access Booking History');
}

function CNX_booking_history()
{
	global $user;
	$customer_id = "";

	if(in_array('exhibitor',$user->roles)){
		$exhibitor_data = new CNXExhibitorManager(0,$user->uid);
		$customer_id = $exhibitor_data->exhibitor->external_ref_id;
		$exhibitorProfileStatus = $exhibitor_data->getExhibitorProfileStatus();

		if($exhibitorProfileStatus === false){
			drupal_goto('/profile/compulsory');
		}
	}

	$obj = new exhBookingHistory($user->uid,$customer_id);
	$vars['historyList'] = $obj->get_list($_POST);
	$vars['optionList'] = $obj->get_action_list();

	$outHTML = TemplateHandler::applyTemplateFile(drupal_get_path('module', 'CNX_BookingHistory') . "/templates/", 'bookinghistory.tpl.php', $vars);
    return $outHTML;
}